version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./mysql_data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: the_zoo

  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    links:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
